---
- name: Restart automation service

  hosts: localhost

  connection: local


  tasks:


    - name: Start Docker container

      community.docker.docker_container:

        name: automation-api

        image: automation-api

        state: started

        restart_policy: always

        ports:
          - "5000:5000"
