name: Cyber Resilience CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  test-api:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.12"


      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt


      - name: Validate Flask application
        run: |
          python -m py_compile app/app.py


  terraform-check:


    runs-on: ubuntu-latest


    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3


      - name: Terraform Init
        working-directory: terraform
        run: terraform init


      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate
